### ISSUE TITLE
能给个springboot配置的demo吗？谢谢

### ISSUE THREAD

**Issue by Daily1116** [binarywang/weixin-java-mp-multi-demo#3]

**Comment by binarywang** [comment]
请移步SDK项目首页查看所有demo

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools

**Comment by Daily1116** [comment]
@binarywang 我说的是配置多个公众号或者企业微信多个应用的spring boot 配置？ 首页那个是单个的

**Comment by binarywang** [comment]
方法都是类似的，你那个看懂了，这个不就很自然会弄了吗？
