### ISSUE TITLE
WxMenu menu = WxMenu.fromJson(a);

### ISSUE THREAD

**Issue by haodetong** [binarywang/weixin-java-mp-multi-demo#4]
WxMenu menu = WxMenu.fromJson(a); 解析不成功

**Comment by binarywang** [comment]
解析不成功，难道不是你的json有问题吗？先检查看要求的格式是什么

**Comment by haodetong** [comment]
我跑的测试烦的源码的json，还有微信开发文档的json。
String a = "{\n" +
                "     \"button\":[\n" +
                "     {    \n" +
                "          \"type\":\"click\",\n" +
                "          \"name\":\"今日歌曲\",\n" +
                "          \"key\":\"V1001_TODAY_MUSIC\"\n" +
                "      },\n" +
                "      {\n" +
                "           \"name\":\"菜单\",\n" +
                "           \"sub_button\":[\n" +
                "           {    \n" +
                "               \"type\":\"view\",\n" +
                "               \"name\":\"搜索\",\n" +
                "               \"url\":\"http://www.soso.com/\"\n" +
                "            },\n" +
                "            {\n" +
                "                 \"type\":\"miniprogram\",\n" +
                "                 \"name\":\"wxa\",\n" +
                "                 \"url\":\"http://mp.weixin.qq.com\",\n" +
                "                 \"appid\":\"wx286b93c14bbf93aa\",\n" +
                "                 \"pagepath\":\"pages/lunar/index\"\n" +
                "             },\n" +
                "            {\n" +
                "               \"type\":\"click\",\n" +
                "               \"name\":\"赞一下我们\",\n" +
                "               \"key\":\"V1001_GOOD\"\n" +
                "            }]\n" +
                "       }]\n" +
                " }\n";

**Comment by binarywang** [comment]
看清用法
